# Generated by Django 4.2.9 on 2024-03-25 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('lesson', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pupils',
        ),
        migrations.AddField(
            model_name='lesson',
            name='pupil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.pupil', verbose_name='pupil'),
        ),
    ]
