version: "3.9"

services:


  my_db:
    image: postgres:16-alpine
    container_name: diploma_container_db
    environment:
      POSTGRES_USER: ${DB_POS_USER}
      POSTGRES_PASSWORD: ${DB_POS_PASSWORD}
      POSTGRES_DB: ${DB_POS_NAME}
    volumes:
        - postgres_data:/var/lib/postgresql/data
    ports:
        - "44444:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${DB_POS_USER} -d ${DB_POS_NAME}" ]
        interval: 10s
        timeout: 5s
        retries: 5
    command: [ "docker-entrypoint.sh", "postgres" ]
volumes:
      postgres_data:
