# Generated by Django 4.2.9 on 2024-03-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet'),
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
    ]
